Upgrade to Rails 7 / Ruby 3

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,35 +1,22 @@
-#!/usr/bin/env sh
+require "fileutils"
 
-# Set up Rails app. Run this script immediately after cloning the codebase.
-# https://github.com/thoughtbot/guides/tree/master/protocol
+APP_ROOT = File.expand_path("..", __dir__)
 
-# Exit if any subcommand fails
-set -e
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Set up Ruby dependencies via Bundler
-gem install bundler --conservative
-bundle check || bundle install
+FileUtils.chdir APP_ROOT do
+  puts "== Installing dependencies =="
+  system! "gem install bundler --conservative"
+  system("bundle check") || system!("bundle install")
 
-# Set up configurable environment variables
-if [ ! -f .env ]; then
-  cp .sample.env .env
-fi
+  puts "\n== Preparing database =="
+  system! "bin/rails db:prepare"
 
-# Set up database and add any development seed data
-bundle exec rails db:setup dev:prime
+  puts "\n== Removing old logs and tempfiles =="
+  system! "bin/rails log:clear tmp:clear"
 
-# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
-mkdir -p .git/safe
-
-# Pick a port for Foreman
-if ! grep --quiet --no-messages --fixed-strings 'port' .foreman; then
-  printf 'port: 3000\n' >> .foreman
-fi
-
-if ! command -v foreman > /dev/null; then
-  gem install foreman
-fi
-
-# Only if this isn't CI
-# if [ -z "$CI" ]; then
-# fi
+  puts "\n== Restarting application server =="
+  system! "bin/rails restart"
+end
